# Generated by Django 5.1.4 on 2026-08-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
