# Generated by Django 6.0.8 on 2026-08-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_profile_ktu_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
