# Generated by Django 6.0.8 on 2026-08-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_images/'),
        ),
    ]
