# Generated by Django 6.0.8 on 2026-08-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_images/'),
        ),
    ]
