# Generated by Django 6.1 on 2026-08-11 09:30

import accounts.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_department_alter_faculty_profile_options_and_more'),
        ('students', '0002_student_profile_profile_image_and_more'),
        ('accounts', '0002_copy_legacy_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_profile',
            options={'ordering': ['fullname'], 'verbose_name_plural': 'student profiles'},
        ),
        migrations.AddField(
            model_name='student_profile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='faculty.course'),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_profile',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='student_profile',
            old_name='department',
            new_name='department_legacy',
        ),
        migrations.AddField(
            model_name='student_profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='faculty.department'),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='ktu_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='ph_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_images/', validators=[accounts.validators.ImageTypeValidator(), accounts.validators.MaxImageSizeValidator()]),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='student_profile',
            index=models.Index(fields=['department', 'course'], name='students_st_departm_c54ee3_idx'),
        ),
    ]
