# Generated by Django 6.1 on 2026-08-15 05:32

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_student_profile_department_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images/', validators=[accounts.validators.ImageTypeValidator(), accounts.validators.MaxImageSizeValidator()]),
        ),
    ]
