# Generated by Django 6.0.8 on 2026-08-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_profile_designation_faculty_profile_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
