# Generated by Django 6.0.8 on 2026-08-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_faculty_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_images'),
        ),
    ]
