# Generated by Django 6.0.8 on 2026-08-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_alter_faculty_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_profile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
