# Generated by Django 6.1 on 2026-08-11 09:30

import accounts.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_faculty_profile_profile_image_and_more'),
        ('students', '0002_student_profile_profile_image_and_more'),
        ('accounts', '0002_copy_legacy_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='faculty_profile',
            options={'verbose_name_plural': 'faculty profiles'},
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='ph_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_images', validators=[accounts.validators.ImageTypeValidator(), accounts.validators.MaxImageSizeValidator()]),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='attendance_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'attendance sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='attendance_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='faculty.attendance_session')),
            ],
            options={
                'verbose_name_plural': 'attendance tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('duration_semesters', models.PositiveSmallIntegerField(default=8)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Department that owns this course.', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='faculty.department')),
            ],
            options={
                'verbose_name_plural': 'courses',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='faculty_profile',
            old_name='department',
            new_name='department_legacy',
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_profiles', to='faculty.department'),
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('semester', models.PositiveSmallIntegerField()),
                ('credits', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_faculty', models.ForeignKey(blank=True, help_text='Faculty member responsible for this subject.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subjects', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='faculty.course')),
            ],
            options={
                'verbose_name_plural': 'subjects',
                'ordering': ['semester', 'name'],
            },
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade_value', models.CharField(blank=True, max_length=2, null=True)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_grades', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student_profile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='faculty.subject')),
            ],
            options={
                'verbose_name_plural': 'grades',
                'ordering': ['semester', 'subject__name'],
            },
        ),
        migrations.AddField(
            model_name='attendance_session',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='faculty.subject'),
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student_profile')),
                ('session', models.ForeignKey(blank=True, help_text='Attendance session this record was created through, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='faculty.attendance_session')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='faculty.subject')),
            ],
            options={
                'verbose_name_plural': 'attendance records',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['course', 'semester'], name='faculty_sub_course__036f97_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'semester'], name='faculty_gra_student_c2a485_idx'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'semester'), name='unique_grade_per_student_subject_semester'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['subject', 'date'], name='faculty_att_subject_c5db88_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'subject'], name='faculty_att_student_7db772_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'date'), name='unique_attendance_per_student_subject_date'),
        ),
    ]
