# Generated by Django 6.1 on 2026-08-11
#
# Repoint the profile/admin `user` foreign keys from the legacy `auth_user`
# table to the new custom user table `accounts_user`.
#
# On databases created before the custom-user swap (i.e. by the fork's
# deployment), the physical FK constraints still reference `auth_user`, even
# though Django's migration state believes they target `settings.AUTH_USER_MODEL`.
# New users are only stored in `accounts_user`, so profile creation for a new
# user fails with a foreign key violation. This migration drops the stale
# constraints and re-creates them against `accounts_user`, preserving each
# constraint's ON DELETE action.
#
# It is a no-op on non-PostgreSQL backends (fresh SQLite/Postgres databases
# already create the constraints pointing at `accounts_user`).

from django.db import migrations

TABLES = {
    "students_student_profile": "ON DELETE CASCADE",
    "faculty_faculty_profile": "ON DELETE CASCADE",
    "django_admin_log": "ON DELETE SET NULL",
}


def _repoint(apps, schema_editor, target="accounts_user"):
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return

    with connection.cursor() as cur:
        cur.execute(
            """
            SELECT con.conrelid::regclass::text,
                   con.conname,
                   att.attname
            FROM pg_constraint con
            JOIN pg_class rel ON rel.oid = con.conrelid
            JOIN pg_attribute att
              ON att.attrelid = con.conrelid AND att.attnum = con.conkey[1]
            WHERE con.contype = 'f'
              AND con.confrelid = 'auth_user'::regclass
            """
        )
        rows = cur.fetchall()

        for table, conname, column in rows:
            if table not in TABLES:
                continue
            cur.execute(
                'ALTER TABLE "{table}" DROP CONSTRAINT "{conname}"'.format(
                    table=table, conname=conname
                )
            )
            cur.execute(
                'ALTER TABLE "{table}" ADD CONSTRAINT "{conname}" '
                'FOREIGN KEY ("{column}") REFERENCES "{target}" ("id") '
                "{delete_action} DEFERRABLE INITIALLY DEFERRED".format(
                    table=table,
                    conname=conname,
                    column=column,
                    target=target,
                    delete_action=TABLES[table],
                )
            )


def repoint_to_accounts_user(apps, schema_editor):
    _repoint(apps, schema_editor, target="accounts_user")


def repoint_to_auth_user(apps, schema_editor):
    _repoint(apps, schema_editor, target="auth_user")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_create_auditlog"),
        ("students", "0008_remove_student_profile_department_legacy"),
        ("faculty", "0008_remove_faculty_profile_department_legacy"),
    ]

    operations = [
        migrations.RunPython(repoint_to_accounts_user, repoint_to_auth_user),
    ]
